### ISSUE TITLE
Stops playing after a few hours

### ISSUE THREAD

**Issue by jdt1** [ServiusHack/MStarPlayer#8]
I am using this player for an exhibition where I use it to send four different tracks to the four output channels of my USB soundcard. It works great, except sometimes a channel will seemingly randomly stop playing. When I click the play button on that track, it will continue playing as if nothing happened. Any idea why this happens?

**Comment by ServiusHack** [comment]
I was able to reproduce this using a very short audio file that was configured to loop in the playlist player. For some reason the loop stops at the end of the file after a few dozen loops. I'll update this issue when I have new information or a fix.

**Comment by ServiusHack** [comment]
Fixed in fc74d70a0bd9dadcdd9195c1fbc9199d517d9e0e
